# Generated by Django 4.1.6 on 2023-02-24 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fooditems', to='Menu.category'),
        ),
    ]
